// import bcrypt from 'bcryptjs';
const bcrypt = require('bcryptjs');

const data = {
  users: [
    {
      name: 'Arham',
      email: 'admin@kickpik.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
    },
    {
      name: 'John',
      email: 'user@gmail.com',
      password: bcrypt.hashSync('7894560', 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      // _id: '1',
      name: 'Nike Sneakers',
      category: 'Shoes',
      gender: `Men's Shoes`,
      image: '/images/product-1.jpg',
      price: '120.53',
      brand: 'Nike',
      rating: 4.5,
      numberOfReviews: 10,
      description: 'High quality product',
      countInStock: 2,
    },
    {
      // _id: `2`,
      name: 'Adidas Sneakers',
      category: 'Shoes',
      gender: `Men's Shoes`,
      image: '/images/product-2.jpg',
      price: '100.50',
      brand: 'Adidas',
      rating: 4.0,
      numberOfReviews: 10,
      description: 'High quality product',
      countInStock: 4,
    },
    {
      // _id: `3`,
      name: `CHUCK 70 Converse`,
      category: 'Shoes',
      gender: `Men's Shoes`,
      image: '/images/product-3.jpg',
      price: '90.55',
      brand: 'Converse',
      rating: 3.7,
      numberOfReviews: 10,
      description: `BRING ON THE RAIN. Iconic style with an explorative feel, the Chuck 70 Counter Climate GORE-TEX High Top brings outdoor ideals to the original '70s design. The Counter Climate style features a water-repellent canvas upper with durable, non-wicking nubuck leather overlays. A waterproof GORE-TEX lining and non-wicking laces offer extra wet weather protection. Paired with colorblocked details and hiker-inspired speed hooks, it's a must-have for the season.`,
      countInStock: 5,
    },
    {
      // _id: `4`,
      name: 'Puma Sneakers',
      category: 'Shoes',
      gender: `Men's Shoes`,
      image: '/images/product-4.jpg',
      price: '110.75',
      brand: 'Puma',
      rating: 4.0,
      numberOfReviews: 10,
      description: 'High quality product',
      countInStock: 3,
    },
    {
      // _id: `5`,
      name: 'Nike Sneakers',
      category: 'Shoes',
      gender: `Men's Shoes`,
      image: '/images/product-5.jpg',
      price: '85.25',
      brand: 'Nike',
      rating: 4.0,
      numberOfReviews: 10,
      description: 'High quality product',
      countInStock: 0,
    },
    {
      // _id: `6`,
      name: 'Gucci Sneakers',
      category: 'Shoes',
      gender: `Men's Shoes`,
      image: '/images/product-6.jpg',
      price: '105.75',
      brand: 'Gucci',
      rating: 5.0,
      numberOfReviews: 10,
      description: 'High quality product',
      countInStock: 2,
    },
  ],
};
module.exports = data;
//export default data;
